listen: 0.0.0.0:8080
listen_pprof: 0.0.0.0:7008
listen_metrics_address: 0.0.0.0:9090
metrics_include_tenant: true

target: 
  endpoint: http://127.0.0.1:9091/receive
  cert_file: ""
  key_file: ""
  ca_file: ""
  insecure_skip_verify: false
enable_ipv6: false
max_conns_per_host: 64

auth:
  egress:
    username: foo
    password: bar

log_level: debug
timeout: 10s
timeout_shutdown: 0s
concurrency: 10
metadata: false
log_response_errors: true

tenant:
  label: tenant
  label_list:
    - tenant
    - other_tenant
  prefix: ""
  prefix_prefer_source: false
  label_remove: true
  header: X-Scope-OrgID
  default: ""
  accept_all: false
